### ISSUE TITLE
Does this module still work?

### ISSUE THREAD

**Issue by torresfabian** [DecidimAustria/decidim-enhanced_textwork#2]
Hello, I have installed this module in a compatible version of decidem and I can't get it to work.
I also tried to see the demos and they didn't work either
https://textwork.decidim-austria.org/

I ask you if the compatibility of the module with Decidim v0.26.0 was broken

**Comment by torresfabian** [comment]
> Hello, I have installed this module in a compatible version of decidem and I can't get it to work. I also tried to see the demos and they didn't work either https://textwork.decidim-austria.org/
> 
> I ask you if the compatibility of the module with Decidim v0.26.0 was broken

**Comment by categulario** [comment]
did you manage to make it work @torresfabian ?

**Comment by arusa** [comment]
Hi! Sorry, I had my notification settings misconfigured and never got notified about your messages. The module should work with Decidim 0.26 and I'm currently working on upgrading it to 0.27.

I also checked our demo instance https://textwork.decidim-austria.org/ and everything seems to work.

What issues do you have?
